name: ZAP API SCAN
on: push

jobs:

  build-image:
    name: Swagger report
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up curl
        uses: 4thel00z/curl-github-action@v0.2.0
      - name: Start Docker Compose (background)
        run:  docker-compose -f "docker-compose.yml" up -d 
        
      - name: Wait For HTTP Responses
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
            url: 'http://localhost:8080/v2/api-docs'
            responseCode: '200'
            timeout: 300000
            interval: 50000
      - name: ZAP Scan for service endpoints
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          format: openapi
          target: 'http://localhost:8080/v2/api-docs'