name: Swagger generation
on: push

jobs:

  build-image:
    name: Swagger report
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Maven Package
        run: |
          cd zap-trial
          mvn clean install -DskipTests
          mvn spring-boot:run
          curl http://localhost:8080/v2/api-docs
          curl http://localhost:8080/v2/api-docs -o myfile.txt          
      - name: save file 
        uses: actions/upload-artifact@v3
        with:
          name: file
          path: zap-trial/myfile.txt